Simplify experiments creation and evaluation
heidmic/suprb-experimentation pull request #28
Opened 2022-11-22 10:41 UTC by RomanSraj

- Update ReadMe
- Add job_id to experiment run
- Update logging_output_scripts to directly use mlflow data

2023-02-14 07:58 UTC, RomanSraj commented
@heidmic all scripts work as expected. Please have a look at the readme and let me know if there is something unclear or missing. If not, please approve the PR

2023-06-02 12:52 UTC, heidmic commented
@RomanSraj can we merge the fixes from https://github.com/heidmic/suprb-experimentation/tree/experiments_working into this PR and merge?

2023-06-02 13:25 UTC, RomanSraj commented
> @RomanSraj can we merge the fixes from https://github.com/heidmic/suprb-experimentation/tree/experiments_working into this PR and merge into master?

Yes we can, although the state of these PRs is in no way clean

2023-06-02 14:18 UTC, heidmic commented
Alright, then I will wait for your "clean" signal

2023-06-09 10:58 UTC, heidmic requested changes

2023-06-09 10:58 UTC, heidmic commented on experiments/mlflow.py
> +                if "Decisioasdn Tree" in experiment.name:
why is there a weird typo?

additionally, I don't think that we, theoretically, want this case in the master to make the code more readable, however, might be the more practical choice

2023-06-09 10:58 UTC, heidmic commented on experiments/mlflow.py
> +                        if "Decisioasdn Tree" in experiment.name:
same as above

2023-06-09 10:58 UTC, heidmic commented on experiments/mlflow.py
> +    n_nodes = estimator.tree_.node_count
is the if missing here?

2023-06-09 10:58 UTC, heidmic commented on logging_output_scripts/config.json
> +        "XCSF",
make this two examples rather than replacing the previous example

2023-12-13 17:30 UTC, heidmic commented
What is missing for merge?

2024-09-10 17:27 UTC, closed without merging

2024-09-10 17:27 UTC, RomanSraj commented
Relevant changes are merged