Comparison of sagas
heidmic/suprb-experimentation pull request #34
Opened 2023-10-24 14:58 UTC by Zatorg

Bachelorarbeit Maximilian Krischan

2023-10-31 14:18 UTC, RomanSraj requested changes
I just left 2 (minor) comments. Although before merging I would consider removing most (or all?) added sbatch files and add in readme how the sbatch file should look like (if it is too different from already available sbatch files).

And most importantly: Please rebase your branch to the current master and resolve the conflicts. I did a quick rebase and took all of your changes (because I didn't want to accidently remove something you added), but I can still see a lot of changes that have (probably) nothing to do with your commit. That most likely comes from another commit that got merged to master in between. 
In the end your PR should only have the relevant changes in it

2023-10-31 14:18 UTC, RomanSraj commented on runs/comparisons/suprb_all_tuning.py
> -            if isinstance(params.solution_composition__crossover__crossover_rate, suprb.optimizer.solution.ga.crossover.NPoint):
Why?

2023-10-31 14:18 UTC, RomanSraj commented on runs/saga_comparison_tests/saga_comparison_tuning.py
> +    def suprb_space(trial: Trial, params: Bunch):
Move parameters that are the same out of the `if/elif`-structure. That way it becomes better readable and the file doesn't become so big

2023-12-13 17:31 UTC, heidmic commented
Are all requested changes integrated?

2023-12-13 18:20 UTC, Zatorg commented
Added some final small changes to make it ready for merge. Could not get more stuff out of the if/elif in the comparison experiment, as the parameters are only shared between some of the compared sagas. Left one example sbatch for the experiment.

2023-12-19 10:31 UTC, heidmic approved these changes

2023-12-19 10:33 UTC, RomanSraj approved these changes

2023-12-19 11:09 UTC, merged